### ISSUE TITLE
Support TravisCI and Danger

### ISSUE THREAD

**Issue by NghiaTranUIT** [airbnb/Lona#63]
## Suggesting a New Feature

In order to keep this repository consistently, and enforce how the people contribute to the project.
I'd like to introduce the Danger in conjunction with TravisCI.

## Summary of Idea

**TravisCI**
One of famous CI server. It's totally free for OSS like Lona. We leverage the CI system in order to run test and build automatically with effortless.

**Danger**
Human can't possibly check everything. For instance, the contributor forget to 
+ Write unit-test
+ Code convention warning by SwiftLint
+ Warning if it's big PR
+ Warning for WIP for Don't Not Merge PR
+ ...

So let the Danger bot do it. It's potential candidate when conjunction with TravisCI.

### Travis
We can inspire how Alamofire construct the [.travis.yml](https://github.com/Alamofire/Alamofire/blob/master/.travis.yml) file.
It should be
```
language: objective-c
osx_image: xcode9
rvm:
  - 2.2.2

env:
  global:
    - WORKSPACE="LonaStudio.xcworkspace"
    - OSX_APP_SCHEME="LonaStudio"
    - OSX_SDK=macosx10.13
  matrix:
    - DESTINATION="arch=x86_64"                      SCHEME="$OSX_APP_SCHEME"           SDK="$OSX_SDK"     RUN_TESTS="YES"    BUILD_EXAMPLE="YES"

before_install:
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list

    # Build Lona
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty;
    fi

    # Run Tests
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -sdk "$SDK" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

```

### Danger
Inspired from [Danger](https://github.com/danger/danger/blob/master/Dangerfile).
According this their [document](http://danger.systems/guides/getting_started.html#creating-a-bot-account-for-danger-to-use). It's super easy to create a bot and integrate to our CI system.

## Requirement
In order to accomplish, I'd like you to 
1. Setup an Travis account as long as authenticating the Lona Repository.
2. According to [Bot's Danger](http://danger.systems/guides/getting_started.html#setting-up-an-access-token), we'd sign up new bot account and grant new `public_repo` token.
Since you're the owner of Lona 👍 

Looking forward to hearing your thought 😄
